#!/bin/bash

# source profile scripts for conda
source ~/.bash_profile

# activate env
conda activate cf-scripts

# make special locks location for conda-build for conda user
mkdir -p ${TMPDIR}/conda_user_conda_build_locks

# Run whatever the user wants.
exec "$@"
